sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/gitberg.git
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+git://github.com/rdhyee/pg-epubmaker.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EXrkarbAycALhSwvg4rRohTN7Km6IcRBmMEQpmd+BNf/gj/+063K4VEKFFYzXfRhr5Eb7GRXn6tRWjTpWoI93Hvz5RHUNxtKM+PfO362F5hjwQK1O6FmUnTfOcJ3934ov1SNcIkGPkBBAh2DiViBl3N2gWWeDzx0GzS0P9rwqCg0ZxTORDJs3KkyaTjGhYvg7T30FL3Fn7MfldOXOuB8aOtmqfe+RK2ro00dxAr54D8euAysK55K6GW8zoIKW/XtbpSt1zOD0mKGTmUTZhH7+6hzmosmGMVO8nSW/tAl1OhUI8/LR1gT3BvuKjTyPuu9os5H7yGz4Sv7HR27zJwZeZSyeNeS+7PM1wP5f+MCFqb1MbBXDBGN1TtEgeoXIuR8bJkAbTyNdBqK8IwSJcf8yWSAjvaQy+EBtBAimOrIVxfifVbNy7id6HKc8uB470wtZVmb9VW85s4JxgeNq0V1okkAPnIvPdGKxCxKXUQvITveJZtdW6aBmQCvSWr59I+/9lOR7Gn+Qyd2duQiYGW6KhqNn/RYR7nOdItz47wTI/G3iy9yDJjCOKN1u3SHFKnGZy2whTfokUekZNG2ijeJOOEzis2COsZ8rhOxHgtdwaa72SKJcyovqeeSFv4mDwuVq+c7BQqVHbxY5zEIM5Cg8DSi0AYde4HnxIWWipsp7wk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: rdhyee/Uncle-Tom-s-Cabin_203
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy